### ISSUE TITLE
Add bottom margin to body element when inspector is collapsed

### ISSUE THREAD

**Issue by dawidurbanski** [ckeditor/ckeditor5-inspector#126]
Currently the margin-bottom on the body element is added when inspector is expanded:

```css
html body.ck-inspector-body-expanded {
    margin-bottom: var(--ck-inspector-height);
}
```

This makes all the content to be nicely pushed up when inspector is expanded

![Screenshot 2021-09-21 at 11 37 32](https://user-images.githubusercontent.com/12466568/134151407-a98ba907-9e7a-480f-92d2-a610ee60a94e.png)

Unfortunately there is no such behaviour in case of inspector collapsed causing contents of the page to overlap with it.

![Screenshot 2021-09-21 at 11 37 46](https://user-images.githubusercontent.com/12466568/134151539-fa8cbd07-0ec4-42c4-b25b-584b704759e2.png)

It would be great if we could add `--ck-inspector-collapsed-height` custom property and use it accordingly:

```css
html body.ck-inspector-body-collapsed {
    margin-bottom: var(--ck-inspector-collapsed-height);
}
```
