### ISSUE TITLE
When resizing, the width of the inspector does not occupy the entire screen

### ISSUE THREAD

**Issue by psmyrek** [ckeditor/ckeditor5-inspector#135]
https://user-images.githubusercontent.com/56868128/144038570-db9b96be-b4e0-4062-b398-0aaf325adb3e.mp4

This is probably introduced by https://github.com/ckeditor/ckeditor5-inspector/pull/130.

Quick fix is to add the following styles, but I'm not sure if this is the right approach to fix this issue:

```css
.ck-inspector-wrapper {
    position: fixed;
    left: 0;
    right: 0;
    z-index: 999;
}
```
